"""Add request_type and details

Revision ID: fe065df75a8e
Revises: 2e3d5cb45a66
Create Date: 2026-06-27 11:22:40.530787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe065df75a8e'
down_revision: Union[str, Sequence[str], None] = '2e3d5cb45a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_requests', sa.Column('request_type', sa.String(), nullable=False))
    op.add_column('registration_requests', sa.Column('details', sa.JSON(), nullable=True))
    op.alter_column('registration_requests', 'serial_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration_requests', 'serial_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('registration_requests', 'details')
    op.drop_column('registration_requests', 'request_type')
    # ### end Alembic commands ###
